modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "xingmot"
description = ""


[[dependencies."${mod_id}"]]
modId = "gtceu"
mandatory = true
versionRange = "[1.4.4,)"
ordering = "AFTER"
side = "BOTH"